# Generated by Django 5.1.1 on 2024-10-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculomodel_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': [('can_visualizar_catalogo', 'Puede ver catálogo')]},
        ),
    ]
