# Generated by Django 5.1.1 on 2024-10-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'ordering': ['-fecha_de_modificacion'], 'permissions': [('can_visualizar_catalogo', 'Puede ver catálogo')], 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
    ]
